Add capybara to Gemfile
Need to add capybara settings to spec_helper to address error message "undefined method `feature' for main:Object (NoMethodError)"

[ticket: 61184130]